language: generic 
sudo: required
services:
    - docker
before_install:
    - docker build -t switchaphon/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true switchaphon/docker-react npm run test